services:
  - type: web
    name: power-arena-exponent-battle
    env: node
    plan: free
    rootDir: MathCode
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
